### ISSUE TITLE
wrong directory in clone script?

### ISSUE THREAD

**Issue by Kirtai** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#157]
The file "clonePackageRepos.sh" starts with the line "cd Cuis-Smalltalk"

Should this be "cd Cuis-Smalltalk-Dev" to match the repo name?

**Comment by jvuletich** [comment]
No, the recommended setup is to have a Cuis-Smalltalk folder that holds Cuis-Smalltalk-Dev and repo folders as siblings.

If you chose to use a different folder instead of 'Cuis-Smalltalk', for instance, an app specific folder, then you need to cd to it yourself.

In any case, the 'cd Cuis-Smalltalk' is harmless. But it might help to avoid cloning all the repos in your home folder in case you forget to cd to your Cuis folder.

**Comment by Kirtai** [comment]
Aha, so that's it. Now I know.

Where is this recommendation written down? I looked but couldn't find it.

The only relevant thing I found was in[this page](https://github.com/Cuis-Smalltalk/Cuis-Smalltalk-Dev/blob/master/Documentation/GettingStarted.md) which says to do:

```
mkdir MyProject
cd MyProject
git clone --depth 1 https://github.com/Cuis-Smalltalk/Cuis-Smalltalk-Dev.git
./Cuis-Smalltalk-Dev/clonePackageRepos.sh
```

Should "MyProject" be replaced with "Cuis-Smalltalk"?

**Comment by jvuletich** [comment]
Just tweaked the install guide to suggest that. Still, MyProject (meaning a project specific name) might be preferred if you're having several Cuis folders in your machine.
